### ISSUE TITLE
Running app.py reports an error

### ISSUE THREAD

**Issue by gl-guoliang** [ChangQingAAS/BingChatGPT-Vue-Chat#1]
##### Error is reported after yaml2 replaces yaml in config.py

MacBook-Pro BingChatGPT-Vue-Chat % /usr/bin/python3 Work/private_code/BingChatGPT-Vue-Chat/server/app.py
2023-02-14 15:01:45.230 | INFO     | __main__:<module>:107 - System initializing...
2023-02-14 15:01:45.536 | ERROR    | __main__:<module>:112 - 错误： Authentication failed
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
2023-02-14 15:01:45.933 | INFO     | __main__:<module>:107 - System initializing...
2023-02-14 15:01:46.206 | ERROR    | __main__:<module>:112 - 错误： Authentication failed
 * Debugger is active!
 * Debugger PIN: 712-749-973
127.0.0.1 - - [14/Feb/2023 15:01:57] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [14/Feb/2023 15:01:58] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by ChangQingAAS** [comment]
额，一开始我做的是一个把BingChatGPT后端和一个前端的组接。
后来，BingChatGPT不开放接口使用了。
我就把后端代码改成基于OPENAI GPT3(ChatGPT的那个模型也不开放了）的一个接口了，但这样也有一个问题：使用的人太多而连接不上。

你可以修改server/app.py和src/components/ChatList.vue/sendMsg()的冗余代码

**Comment by ChangQingAAS** [comment]
Noting:
- At the beginning of this project, I did a combination of BingChatGPT backend and a Vue frontend.
- Later, BingChatGPT did not open the API interface for use.
- Then, I changed the back-end code to an API interface based on OPENAI GPT3 (because ChatGPT is not open anymore), but there is also a problem: too many people use this API, which may cause the connection to fail.

You can modify the redundant code of server/app.py and src/components/ChatList.vue/sendMsg()
